<?php
return [
“To see a world in a grain of sand.” - William Blake,
“The tygers of wrath are wiser than the horses of instruction.” - William Blake,
“Joy and woe are woven fine.” - William Blake,
“He who desires but acts not breeds pestilence.” - William Blake,
“The road of excess leads to the palace of wisdom.” - William Blake,
“If the doors of perception were cleansed everything would appear to man as it is, infinite.” - William Blake,
“A truth that's told with bad intent beats all the lies you can invent.” - William Blake,
“Exuberance is beauty.” - William Blake,
“Improvement makes straight roads, but the crooked roads without improvement are roads of genius.” - William Blake,
“There is nothing either good or bad, but thinking makes it so.” - William Shakespeare,
“All the world’s a stage, and all the men and women merely players.” - William Shakespeare,
“The better part of valour is discretion.” - William Shakespeare,
“The fault, dear Brutus, is not in our stars, but in ourselves.” - William Shakespeare,
“Cowards die many times before their deaths.” - William Shakespeare,
“Brevity is the soul of wit.” - William Shakespeare,
“Love looks not with the eyes, but with the mind.” - William Shakespeare,
“We are such stuff as dreams are made on.” - William Shakespeare,
“Sweet are the uses of adversity.” - William Shakespeare,
“Uneasy lies the head that wears a crown.” - William Shakespeare,
“Beauty is truth, truth beauty—that is all ye know on earth, and all ye need to know.” - John Keats,
“A thing of beauty is a joy forever.” - John Keats,
“Heard melodies are sweet, but those unheard are sweeter.” - John Keats,
“I have been half in love with easeful Death.” - John Keats,
“Thou wast not born for death, immortal Bird.” - John Keats,
“Season of mists and mellow fruitfulness.” - John Keats,
“When I have fears that I may cease to be.” - John Keats,
“Love is my religion—I could die for that.” - John Keats,
“Darkling I listen.” - John Keats,
“She dwells with Beauty—Beauty that must die.” - John Keats,
“I wandered lonely as a cloud.” - William Wordsworth,
“The child is father of the man.” - William Wordsworth,
“Our birth is but a sleep and a forgetting.” - William Wordsworth,
“The world is too much with us; late and soon.” - William Wordsworth,
“Trailing clouds of glory do we come.” - William Wordsworth,
“The still sad music of humanity.” - William Wordsworth,
“The best portion of a good man's life: his little, nameless, unremembered acts of kindness and of love.” - William Wordsworth,
“Poetry is the spontaneous overflow of powerful feelings.” - William Wordsworth,
“Fill your paper with the breathings of your heart.” - William Wordsworth,
“The soul that rises with us, our life’s star.” - William Wordsworth,
“Because I could not stop for Death, he kindly stopped for me.” - Emily Dickinson,
“Hope is the thing with feathers.” - Emily Dickinson,
“I’m nobody! Who are you?” - Emily Dickinson,
“Tell all the truth but tell it slant.” - Emily Dickinson,
“Much madness is divinest sense.” - Emily Dickinson,
“I heard a fly buzz when I died.” - Emily Dickinson,
“After great pain, a formal feeling comes.” - Emily Dickinson,
“I dwell in possibility.” - Emily Dickinson,
“The brain is wider than the sky.” - Emily Dickinson,
“Pain has an element of blank.” - Emily Dickinson,
“To strive, to seek, to find, and not to yield.” - Alfred Tennyson,
“I am half-sick of shadows,” said the Lady of Shalott. - Alfred Tennyson,
“Hope smiles from the threshold of the year to come.” - Alfred Tennyson,
“The old order changeth, yielding place to new.” - Alfred Tennyson,
“Tears, idle tears, I know not what they mean.” - Alfred Tennyson,
“Theirs not to reason why, theirs but to do and die.” - Alfred Tennyson,
“Knowledge comes, but wisdom lingers.” - Alfred Tennyson,
“Ring out the false, ring in the true.” - Alfred Tennyson,
“So sad, so strange, the days that are no more.” - Alfred Tennyson,
“My strength is as the strength of ten, because my heart is pure.” - Alfred Tennyson,
“No man is an island, entire of itself.” - John Donne,
“Death, be not proud, though some have called thee mighty and dreadful.” - John Donne,
“Love, all alike, no season knows nor clime.” - John Donne,
“When thou weep’st, unkindly kind.” - John Donne,
“More than kisses, letters mingle souls.” - John Donne,
“I am two fools, I know, for loving, and for saying so.” - John Donne,
“Our two souls therefore, which are one.” - John Donne,
“Thou hast made me, and shall thy work decay?” - John Donne,
“Batter my heart, three-person’d God.” - John Donne,
“This is my play’s last scene.” - John Donne,
“Had we but world enough, and time.” - Andrew Marvell,
“The grave’s a fine and private place, but none, I think, do there embrace.” - Andrew Marvell,
“But at my back I always hear time’s wingèd chariot hurrying near.” - Andrew Marvell,
“Let us roll all our strength and all our sweetness up into one ball.” - Andrew Marvell,
“Now let us sport us while we may.” - Andrew Marvell,
“The iron gates of life.” - Andrew Marvell,
“The youthful hue sits on thy skin like morning dew.” - Andrew Marvell,
“Love’s mysteries in souls do grow.” - Andrew Marvell,
“Annihilate but space and time.” - Andrew Marvell,
“Deserts of vast eternity.” - Andrew Marvell,
“April is the cruellest month.” - T. S. Eliot,
“I have measured out my life with coffee spoons.” - T. S. Eliot,
“Do I dare disturb the universe?” - T. S. Eliot,
“This is the way the world ends, not with a bang but a whimper.” - T. S. Eliot,
“Footfalls echo in the memory.” - T. S. Eliot,
“In the room the women come and go talking of Michelangelo.” - T. S. Eliot,
“The yellow fog that rubs its back upon the window-panes.” - T. S. Eliot,
“I grow old … I grow old … I shall wear the bottoms of my trousers rolled.” - T. S. Eliot,
“Let us go then, you and I.” - T. S. Eliot,
“Between the idea and the reality falls the shadow.” - T. S. Eliot,
“Things fall apart; the centre cannot hold.” - W. B. Yeats,
“A terrible beauty is born.” - W. B. Yeats,
“Tread softly because you tread on my dreams.” - W. B. Yeats,
“The best lack all conviction, while the worst are full of passionate intensity.” - W. B. Yeats,
“Education is not the filling of a pail, but the lighting of a fire.” - W. B. Yeats,
“The ceremony of innocence is drowned.” - W. B. Yeats,
“I have spread my dreams under your feet.” - W. B. Yeats,
“The horror! The horror!” - Joseph Conrad,
“We live, as we dream—alone.” - Joseph Conrad,
“Your strength is just an accident arising from the weakness of others.” - Joseph Conrad,
“There is a taint of death, a flavour of mortality in lies.” - Joseph Conrad,
“The conquest of the earth is not a pretty thing.” - Joseph Conrad,
“A haze rested on the low shores.” - Joseph Conrad,
“The mind of man is capable of anything.” - Joseph Conrad,
“Droll thing life is—that mysterious arrangement of merciless logic.” - Joseph Conrad,
“I don’t like work. I had rather laze around and think of all the fine things that can be done.” - Joseph Conrad,
“The sea has never been friendly to man.” - Joseph Conrad,
“Call me Ishmael.” - Herman Melville,
“From hell’s heart I stab at thee.” - Herman Melville,
“It is not down in any map; true places never are.” - Herman Melville,
“Better to sleep with a sober cannibal than a drunken Christian.” - Herman Melville,
“Ignorance is the parent of fear.” - Herman Melville,
“A smile is the chosen vehicle of all ambiguities.” - Herman Melville,
“There are certain queer times and occasions in this strange mixed affair we call life.” - Herman Melville,
“Genius, all over the world, stands hand in hand.” - Herman Melville,
“There is no folly of the beast of the earth which is not infinitely outdone by the madness of men.” - Herman Melville,
“Truth is in things, not in words.” - Herman Melville,
“It was the best of times, it was the worst of times.” - Charles Dickens,
“Have a heart that never hardens, and a temper that never tires.” - Charles Dickens,
“No one is useless in this world who lightens the burden of it to anyone else.” - Charles Dickens,
“There is nothing so strong or safe in an emergency of life as the simple truth.” - Charles Dickens,
“Reader, I married him.” - Charlotte Brontë,
“I am no bird; and no net ensnares me.” - Charlotte Brontë,
“I would always rather be happy than dignified.” - Charlotte Brontë,
“Life appears to me too short to be spent in nursing animosity.” - Charlotte Brontë,
“I am not an angel, and I will not be one till I die.” - Charlotte Brontë,
“I care for myself. The more solitary, the more friendless, the more unsustained I am, the more I will respect myself.” - Charlotte Brontë,
“I am a free human being with an independent will.” - Charlotte Brontë,
“Prejudices, it is well known, are most difficult to eradicate from the heart.” - Charlotte Brontë,
“Conventionality is not morality.” - Charlotte Brontë,
“The soul, fortunately, has an interpreter — often an unconscious but still a faithful interpreter — in the eye.” - Charlotte Brontë,
“There is no charm equal to tenderness of heart.” - Jane Austen,
“I declare after all there is no enjoyment like reading.” - Jane Austen,
“Angry people are not always wise.” - Jane Austen,
“A lady's imagination is very rapid; it jumps from admiration to love, from love to matrimony in a moment.” - Jane Austen,
“Vanity and pride are different things.” - Jane Austen,
“To be fond of dancing was a certain step towards falling in love.” - Jane Austen,
“You must be the best judge of your own happiness.” - Jane Austen,
“There are people, who the more you do for them, the less they will do for themselves.” - Jane Austen,
“It isn't what we say or think that defines us, but what we do.” - Jane Austen,
“Think only of the past as its remembrance gives you pleasure.” - Jane Austen,
“I am Heathcliff.” - Emily Brontë,
“Whatever our souls are made of, his and mine are the same.” - Emily Brontë,
“He's more myself than I am.” - Emily Brontë,
“I wish I were a girl again, half savage and hardy.” - Emily Brontë,
“I cannot live without my soul.” - Emily Brontë,
“Terror made me cruel.” - Emily Brontë,
“I have not broken your heart — you have broken it.” - Emily Brontë,
“I’ll be as dirty as I please, and I like to be dirty.” - Emily Brontë,
“I’ll walk where my own nature would be leading.” - Emily Brontë,
“He wanted all to lie in an ecstasy of peace.” - Emily Brontë,
“I am not afraid of storms, for I am learning how to sail my ship.” - Louisa May Alcott,
“She is too fond of books, and it has turned her brain.” - Louisa May Alcott,
“I like good strong words that mean something.” - Louisa May Alcott,
“I’d rather take coffee than compliments just now.” - Louisa May Alcott,
“I want to do something splendid before I go into my castle.” - Louisa May Alcott,
“I’m not afraid of being poor.” - Louisa May Alcott,
“Let us be elegant or die.” - Louisa May Alcott,
“I am not a genius, but I have a great deal of patience.” - Louisa May Alcott,
“Love is a great beautifier.” - Louisa May Alcott,
“I’d rather be a free spinster and paddle my own canoe.” - Louisa May Alcott,
“The man who does not read has no advantage over the man who cannot read.” - Mark Twain,
“Whenever you find yourself on the side of the majority, it is time to pause and reflect.” - Mark Twain,
“Kindness is the language which the deaf can hear and the blind can see.” - Mark Twain,
“The secret of getting ahead is getting started.” - Mark Twain,
“Courage is resistance to fear, mastery of fear — not absence of fear.” - Mark Twain,
“Truth is stranger than fiction.” - Mark Twain,
“Never put off till tomorrow what you can do the day after tomorrow.” - Mark Twain,
“Good friends, good books, and a sleepy conscience: this is the ideal life.” - Mark Twain,
“The lack of money is the root of all evil.” - Mark Twain,
“Get your facts first, then you can distort them as you please.” - Mark Twain,
“I celebrate myself, and sing myself.” - Walt Whitman,
“I am large, I contain multitudes.” - Walt Whitman,
“Do I contradict myself? Very well then I contradict myself.” - Walt Whitman,
“The powerful play goes on, and you may contribute a verse.” - Walt Whitman,
“Be curious, not judgmental.” - Walt Whitman,
“I sound my barbaric yawp over the roofs of the world.” - Walt Whitman,
“Every atom belonging to me as good belongs to you.” - Walt Whitman,
“I discover myself on the verge of a usual mistake.” - Walt Whitman,
“I too am not a bit tamed.” - Walt Whitman,
“I exist as I am, that is enough.” - Walt Whitman,
“The past is not dead. It is not even past.” - William Faulkner,
“You cannot swim for new horizons until you have courage to lose sight of the shore.” - William Faulkner,
“The man who removes a mountain begins by carrying away small stones.” - William Faulkner,
“Don’t bother just to be better than your contemporaries or predecessors. Try to be better than yourself.” - William Faulkner,
“Always dream and shoot higher than you know you can do.” - William Faulkner,
“Given a choice between grief and nothing, I’d choose grief.” - William Faulkner,
“Memory believes before knowing remembers.” - William Faulkner,
“The end of wisdom is to dream high enough not to lose the dream in the seeking of it.” - William Faulkner,
“A writer needs three things: experience, observation, and imagination.” - William Faulkner,
“The salvation of man is through love and in love.” - William Faulkner,
“The heart wants what it wants.” - Emily Dickinson,
“I felt it shelter to speak to you.” - Emily Dickinson,
“Forever is composed of nows.” - Emily Dickinson,
“The soul should always stand ajar.” - Emily Dickinson,
“I’m ceded—I’ve stopped being theirs.” - Emily Dickinson,
“The soul unto itself is an imperial friend.” - Emily Dickinson,
“Not knowing when the dawn will come, I open every door.” - Emily Dickinson,
“The soul selects her own society.” - Emily Dickinson,
“Success is counted sweetest by those who ne’er succeed.” - Emily Dickinson,
“Tell the truth but tell it slant.” - Emily Dickinson,
“The mind is its own place, and in itself can make a Heaven of Hell, a Hell of Heaven.” - John Milton,
“Better to reign in Hell than serve in Heaven.” - John Milton,
“Long is the way and hard, that out of Hell leads up to light.” - John Milton,
“Awake, arise, or be forever fallen.” - John Milton,
“The star that bids the shepherd fold.” - John Milton,
“The world was all before them.” - John Milton,
“Thick as autumnal leaves that strow the brooks.” - John Milton,
“The mind can make a prison of paradise.” - John Milton,
“What reinforcement we may gain from hope.” - John Milton,
“The angelic guards ascended.” - John Milton,
“The music in my heart I bore.” - William Wordsworth,
“The sky is everywhere, it begins at your feet.” - Jandy Nelson,
“Grief is forever. It doesn't go away.” - Jandy Nelson,
“If you’re not careful, grief will steal everything you have left.” - Jandy Nelson,
“Love is so much more complicated than anyone ever tells you.” - Jandy Nelson,
“You can tell your story any way you want.” - Jandy Nelson,
“The heart is a thousand-stringed instrument.” - Jandy Nelson,
“I think you can sort of slip out of your life and into someone else's.” - Jandy Nelson,
“You are all the colors in one, at full brightness.” - Jandy Nelson,
“I want to be the one who makes you feel infinite.” - Jandy Nelson,
“I think you can miss someone even more than you loved them.” - Jandy Nelson,
“Keep a little fire burning; however small, however hidden.” - Cormac McCarthy,
“Each the other's world entire.” - Cormac McCarthy,
“Nobody wants to be here and nobody wants to leave.” - Cormac McCarthy,
“You have to carry the fire.” - Cormac McCarthy,
“There is no God and we are his prophets.” - Cormac McCarthy,
“The things you put into your head are there forever.” - Cormac McCarthy,
“He walked out in the gray light and stood.” - Cormac McCarthy,
“You have my whole heart. You always did.” - Cormac McCarthy,
“The universe is made of stories, not atoms.” - Muriel Rukeyser,
“What would happen if one woman told the truth about her life?” - Muriel Rukeyser,
“The world would split open.” - Muriel Rukeyser,
“Breathe-in experience, breathe-out poetry.” - Muriel Rukeyser,
“Poetry is not a luxury.” - Muriel Rukeyser,
“The journey is my home.” - Muriel Rukeyser,
“I lived in the first century of world wars.” - Muriel Rukeyser,
“I am in the world to change the world.” - Muriel Rukeyser,
“The fear of poetry is the fear of possibility.” - Muriel Rukeyser,
“Truth is a matter of the imagination.” - Muriel Rukeyser,
“No one can make you feel inferior without your consent.” - Eleanor Roosevelt,
“Do one thing every day that scares you.” - Eleanor Roosevelt,
“Happiness is not a goal; it is a by-product.” - Eleanor Roosevelt,
“You must do the things you think you cannot do.” - Eleanor Roosevelt,
“With freedom comes responsibility.” - Eleanor Roosevelt,
“The giving of love is an education in itself.” - Eleanor Roosevelt,
“Understanding is a two-way street.” - Eleanor Roosevelt,
“You gain strength, courage, and confidence by every experience.” - Eleanor Roosevelt,
“To live will be an awfully big adventure.” - J. M. Barrie,
“Dreams do come true, if only we wish hard enough.” - J. M. Barrie,
“Never say goodbye because goodbye means going away.” - J. M. Barrie,
“All children, except one, grow up.” - J. M. Barrie,
“Stars are beautiful, but they may not take part in anything.” - J. M. Barrie,
“It is only with the heart that one can see rightly.” - Antoine de Saint-Exupéry,
“What is essential is invisible to the eye.” - Antoine de Saint-Exupéry,
“You become responsible, forever, for what you have tamed.” - Antoine de Saint-Exupéry,
“All grown-ups were once children.” - Antoine de Saint-Exupéry,
“The eyes are blind. One must look with the heart.” - Antoine de Saint-Exupéry,
“Straight ahead you can’t go very far.” - Antoine de Saint-Exupéry,
“Language is the source of misunderstandings.” - Antoine de Saint-Exupéry,
“You know... one loves the sunset, when one is so sad.” - Antoine de Saint-Exupéry,
“There is nothing noble in being superior to your fellow man.” - Ernest Hemingway,
“Courage is grace under pressure.” - Ernest Hemingway,
“Happiness in intelligent people is the rarest thing I know.” - Ernest Hemingway,
“Write hard and clear about what hurts.” - Ernest Hemingway,
“Never confuse movement with action.” - Ernest Hemingway,
“The sun also rises.” - Ernest Hemingway,
“Eighty percent of success is showing up.” - Woody Allen,
“I'm not afraid to die, I just don't want to be there when it happens.” - Woody Allen,
“I don't know the question, but sex is definitely the answer.” - Woody Allen,
“I'm not a real film-maker. I'm a fake film-maker.” - Woody Allen,
“The talent for being happy is appreciating and liking what you have.” - Woody Allen,
“I'm not a hypochondriac, I'm an alarmist.” - Woody Allen,
“Imagination is more important than knowledge.” - Albert Einstein,
“The important thing is not to stop questioning.” - Albert Einstein,
“I have no special talent. I am only passionately curious.” - Albert Einstein,
“A person who never made a mistake never tried anything new.” - Albert Einstein,
“Reality is merely an illusion, albeit a very persistent one.” - Albert Einstein,
“I write entirely to find out what I’m thinking.” - Joan Didion,
“Character — the willingness to accept responsibility for one’s own life.” - Joan Didion,
“We tell ourselves stories in order to live.” - Joan Didion,
“Grammar is a piano I play by ear.” - Joan Didion,
“To free us from the expectations of others.” - Joan Didion,
“The ability to think for oneself depends on one’s mastery of the language.” - Joan Didion,
“Memory fades, memory adjusts, memory conforms to what we think we remember.” - Joan Didion,
“I’m not sure I ever loved the world.” - Joan Didion,
“Life changes fast. Life changes in the instant.” - Joan Didion,
“A classic is a book that has never finished saying what it has to say.” - Italo Calvino,
“The more enlightened our houses are, the more their walls ooze ghosts.” - Italo Calvino,
“The city does not tell its past, but contains it like the lines of a hand.” - Italo Calvino,
“The universe will express itself as long as someone listens.” - Italo Calvino,
“Everything can change, but not the language that we carry inside us.” - Italo Calvino,
“The only truth is that nothing is true.” - Italo Calvino,
“The desire to understand the world is the first step toward changing it.” - Italo Calvino,
“The invisible cities are always there.” - Italo Calvino,
“The distance between the voice and the ear is infinite.” - Italo Calvino,
“We live on a placid island of ignorance.” - H. P. Lovecraft,
“The oldest and strongest emotion of mankind is fear.” - H. P. Lovecraft,
“The oldest and strongest kind of fear is fear of the unknown.” - H. P. Lovecraft,
“Unhallowed blasphemies were spoken.” - H. P. Lovecraft,
“The world is indeed comic, but the joke is on mankind.” - H. P. Lovecraft,
“I could not help feeling that they were evil things.” - H. P. Lovecraft,
“The dreams in which I’m dying are the best I’ve ever had.” - H. P. Lovecraft,
“That is not dead which can eternal lie.” - H. P. Lovecraft,
“With strange aeons even death may die.” - H. P. Lovecraft,
“The truth will set you free, but first it will make you miserable.” - James A. Garfield,
“Ideas are the great warriors of the world.” - James A. Garfield,
“The chief duty of government is to keep the peace.” - James A. Garfield,
“A pound of pluck is worth a ton of luck.” - James A. Garfield,
“Next in importance to freedom and justice is popular education.” - James A. Garfield,
“The sin of silence when they should protest makes cowards of men.” - James A. Garfield,
“The truth is too simple for us.” - James A. Garfield,
“The strength of a nation lies in the homes of its people.” - James A. Garfield,
“The best education will not save us from ourselves.” - James A. Garfield,
“I am not what happened to me, I am what I choose to become.” - Carl Jung,
“Your vision will become clear only when you look into your heart.” - Carl Jung,
“The privilege of a lifetime is to become who you truly are.” - Carl Jung,
“People will do anything, no matter how absurd, to avoid facing their own souls.” - Carl Jung,
“Who looks outside, dreams; who looks inside, awakes.” - Carl Jung,
“The shoe that fits one person pinches another.” - Carl Jung,
“The only way out of the labyrinth of suffering is to forgive.” - John Green,
“Some infinities are bigger than other infinities.” - John Green,
“Grief does not change you. It reveals you.” - John Green,
“The town was paper, but the memories were not.” - John Green,
“My thoughts are stars I cannot fathom into constellations.” - John Green,
“The marks humans leave are too often scars.” - John Green,
“I go to seek a Great Perhaps.” - John Green,
“Do not wait to strike till the iron is hot; but make it hot by striking.” - W. B. Yeats,
“Think where man’s glory most begins and ends.” - W. B. Yeats,
“The innocent and the beautiful have no enemy but time.” - W. B. Yeats,
“I have believed the best of every man.” - W. B. Yeats,
“The intellect of man is forced to choose.” - W. B. Yeats,
“Too long a sacrifice can make a stone of the heart.” - W. B. Yeats,
“The winds of change are always blowing.” - W. B. Yeats,
“The soul becomes dyed with the color of its thoughts.” - Marcus Aurelius,
“You have power over your mind — not outside events.” - Marcus Aurelius,
“The happiness of your life depends upon the quality of your thoughts.” - Marcus Aurelius,
“Waste no more time arguing what a good man should be. Be one.” - Marcus Aurelius,
“If it is not right, do not do it.” - Marcus Aurelius,
“The impediment to action advances action.” - Marcus Aurelius,
“Accept the things to which fate binds you.” - Marcus Aurelius,
“The best revenge is not to be like your enemy.” - Marcus Aurelius,
“Dwell on the beauty of life.” - Marcus Aurelius,
“The man who moves a mountain begins by carrying away small stones.” - Confucius,
“It does not matter how slowly you go as long as you do not stop.” - Confucius,
“Our greatest glory is not in never falling, but in rising every time we fall.” - Confucius,
“When we see men of worth, we should think of equaling them.” - Confucius,
“The superior man is modest in his speech but exceeds in his actions.” - Confucius,
“The most wasted of all days is one without laughter.” - E. E. Cummings,
“It takes courage to grow up and become who you really are.” - E. E. Cummings,
“I carry your heart with me - I carry it in my heart.” - E. E. Cummings,
“Unbeing dead isn’t being alive.” - E. E. Cummings,
“To be nobody but yourself in a world which is doing its best to make you everybody else.” - E. E. Cummings,
“Love is the voice under all silences.” - E. E. Cummings,
“Kisses are a better fate than wisdom.” - E. E. Cummings,
“The earth laughs in flowers.” - E. E. Cummings,
“I’d rather learn from one bird how to sing than teach ten thousand stars how not to dance.” - E. E. Cummings,
“The only truth is growth.” - E. E. Cummings,
“The man who does not read good books has no advantage over the man who cannot read them.” - Mark Twain,
“Never argue with stupid people, they will drag you down to their level and then beat you with experience.” - Mark Twain,
“Courage is resistance to fear, mastery of fear, not absence of fear.” - Mark Twain,
“Truth is stranger than fiction, but it is because fiction is obliged to stick to possibilities.” - Mark Twain,
“All animals are equal, but some animals are more equal than others.” - George Orwell,
“If liberty means anything at all, it means the right to tell people what they do not want to hear.” - George Orwell,
“Freedom is the freedom to say that two plus two make four.” - George Orwell,
“In a time of deceit telling the truth is a revolutionary act.” - George Orwell,
“Big Brother is watching you.” - George Orwell,
“The most effective way to destroy people is to deny and obliterate their own understanding of their history.” - George Orwell,
“The choice for mankind lies between freedom and happiness.” - George Orwell,
“Power is in tearing human minds to pieces and putting them together again in new shapes.” - George Orwell,
“Reality exists in the human mind, and nowhere else.” - George Orwell,
“Perhaps one did not want to be loved so much as to be understood.” - George Orwell,
“The only way to deal with an unfree world is to become so absolutely free that your very existence is an act of rebellion.” - Albert Camus,
“In the depth of winter, I finally learned that within me there lay an invincible summer.” - Albert Camus,
“Blessed are the hearts that can bend; they shall never be broken.” - Albert Camus,
“Man is the only creature who refuses to be what he is.” - Albert Camus,
“Don’t walk behind me; I may not lead. Don’t walk in front of me; I may not follow. Just walk beside me and be my friend.” - Albert Camus,
“The purpose of a writer is to keep civilization from destroying itself.” - Albert Camus,
“You will never be happy if you continue to search for what happiness consists of.” - Albert Camus,
“A man without ethics is a wild beast loosed upon this world.” - Albert Camus,
“Freedom is nothing but a chance to be better.” - Albert Camus,
“Live to the point of tears.” - Albert Camus,
“We are all apprentices in a craft where no one ever becomes a master.” - Ernest Hemingway,
“The world breaks everyone, and afterward, many are strong at the broken places.” - Ernest Hemingway,
“The best way to find out if you can trust somebody is to trust them.” - Ernest Hemingway,
“You can’t get away from yourself by moving from one place to another.” - Ernest Hemingway,
“The most essential gift for a good writer is a built-in, shockproof bullshit detector.” - Ernest Hemingway,
“You don’t have to burn books to destroy a culture. Just get people to stop reading them.” - Ray Bradbury,
“Stuff your eyes with wonder.” - Ray Bradbury,
“You must stay drunk on writing so reality cannot destroy you.” - Ray Bradbury,
“We are an impossibility in an impossible universe.” - Ray Bradbury,
“Jump, and you will find out how to unfold your wings as you fall.” - Ray Bradbury,
“Love what you do and do what you love.” - Ray Bradbury,
“There is more than one way to burn a book.” - Ray Bradbury,
“You have to know how to accept rejection and reject acceptance.” - Ray Bradbury,
“Don’t think. Thinking is the enemy of creativity.” - Ray Bradbury,
“We never sit anything out. We are always waging war.” - Ray Bradbury,
“The worst enemy to creativity is self-doubt.” - Sylvia Plath,
“I shut my eyes and all the world drops dead.” - Sylvia Plath,
“I took a deep breath and listened to the old brag of my heart.” - Sylvia Plath,
“I am inhabited by a cry.” - Sylvia Plath,
“I talk to God but the sky is empty.” - Sylvia Plath,
“The silence depressed me.” - Sylvia Plath,
“I felt my lungs inflate with the onrush of scenery.” - Sylvia Plath,
“I want to live and feel all the shades, tones and variations of mental and physical experience.” - Sylvia Plath,
“I am too pure for you or anyone.” - Sylvia Plath,
“I am afraid of getting older. I am afraid of getting married.” - Sylvia Plath,
“The mind is its own place.” - John Milton,
“Long is the way and hard.” - John Milton,
“Thick as autumnal leaves.” - John Milton,
“You have power over your mind.” - Marcus Aurelius,
“Waste no more time arguing what a good man should be.” - Marcus Aurelius,
“Look well into thyself.” - Marcus Aurelius,
“The truth is rarely pure and never simple.” - Oscar Wilde,
“To define is to limit.” - Oscar Wilde,
“A little sincerity is a dangerous thing.” - Oscar Wilde,
“The only difference between the saint and the sinner is that every saint has a past.” - Oscar Wilde,
“The books that the world calls immoral are books that show the world its own shame.” - Oscar Wilde,
“Art is the most beautiful of all lies.” - Oscar Wilde,
“The public is wonderfully tolerant. It forgives everything except genius.” - Oscar Wilde,
“The soul is born old but grows young.” - Oscar Wilde,
“The aim of life is self-development.” - Oscar Wilde,
“The mystery of love is greater than the mystery of death.” - Oscar Wilde,
“The past is never where you think you left it.” - Katherine Anne Porter,
“Love must be learned, and learned again.” - Katherine Anne Porter,
“The future is not one of the options.” - Katherine Anne Porter,
“The real sin against life is to abuse and destroy beauty.” - Katherine Anne Porter,
“I shall try to tell the truth, but the result will be fiction.” - Katherine Anne Porter,
“Human life itself may be almost pure chaos.” - Katherine Anne Porter,
“The illusion of love is the most dangerous illusion of all.” - Katherine Anne Porter,
“The past is never dead. It is not even past.” - Katherine Anne Porter,
“The only real ending is death.” - Katherine Anne Porter,
“The truth is not always the same as the facts.” - Katherine Anne Porter,
“The world is full of obvious things which nobody ever observes.” - Arthur Conan Doyle,
“When you have eliminated the impossible, whatever remains, however improbable, must be the truth.” - Arthur Conan Doyle,
“It is a capital mistake to theorize before one has data.” - Arthur Conan Doyle,
“The emotional qualities are antagonistic to clear reasoning.” - Arthur Conan Doyle,
“Education never ends, Watson.” - Arthur Conan Doyle,
“I never guess. It is a shocking habit.” - Arthur Conan Doyle,
“There is nothing more deceptive than an obvious fact.” - Arthur Conan Doyle,
“You see, but you do not observe.” - Arthur Conan Doyle,
“The little things are infinitely the most important.” - Arthur Conan Doyle,
“Mediocrity knows nothing higher than itself.” - Arthur Conan Doyle,
“The world is a fine place and worth fighting for.” - Ernest Hemingway,
“There is no friend as loyal as a book.” - Ernest Hemingway,
“You are so brave and quiet I forget you are suffering.” - Ernest Hemingway,
“The most painful thing is losing yourself in the process of loving someone too much.” - Ernest Hemingway,
“The best people possess a feeling for beauty.” - Ernest Hemingway,
“The world breaks everyone.” - Ernest Hemingway,
“We are all broken, that’s how the light gets in.” - Ernest Hemingway,
“I love sleep. My life has the tendency to fall apart when I'm awake.” - Ernest Hemingway,
“Never go on trips with anyone you do not love.” - Ernest Hemingway,
“The universe is not only stranger than we imagine, it is stranger than we can imagine.” - J. B. S. Haldane,
“Theories crumble, but good observations never fade.” - J. B. S. Haldane,
“Reality is not only stranger than fiction, it is more complex.” - J. B. S. Haldane,
“The world shall perish not for lack of wonders, but for lack of wonder.” - J. B. S. Haldane,
“Science is the belief in the ignorance of experts.” - J. B. S. Haldane,
“The most revolutionary thing one can do is always to proclaim loudly what is happening.” - J. B. S. Haldane,
“The truth is rarely simple and never pure.” - J. B. S. Haldane,
“The universe is not required to be in perfect harmony with human ambition.” - J. B. S. Haldane,
“The future will be better tomorrow.” - J. B. S. Haldane,
“The most important thing is not to stop questioning.” - J. B. S. Haldane,
“The arc of the moral universe is long, but it bends toward justice.” - Martin Luther King Jr.,
“Darkness cannot drive out darkness; only light can do that.” - Martin Luther King Jr.,
“Injustice anywhere is a threat to justice everywhere.” - Martin Luther King Jr.,
“Faith is taking the first step even when you don’t see the whole staircase.” - Martin Luther King Jr.,
“Our lives begin to end the day we become silent about things that matter.” - Martin Luther King Jr.,
“The time is always right to do what is right.” - Martin Luther King Jr.,
“Love is the only force capable of transforming an enemy into a friend.” - Martin Luther King Jr.,
“We must accept finite disappointment, but never lose infinite hope.” - Martin Luther King Jr.,
“Life’s most persistent and urgent question is, ‘What are you doing for others?’” - Martin Luther King Jr.,
“Freedom is never voluntarily given by the oppressor.” - Martin Luther King Jr.,
“The only thing necessary for the triumph of evil is for good men to do nothing.” - Edmund Burke,
“Nobody made a greater mistake than he who did nothing because he could do only a little.” - Edmund Burke,
“The greater the power, the more dangerous the abuse.” - Edmund Burke,
“All tyranny needs to gain a foothold is for people of good conscience to remain silent.” - Edmund Burke,
“Rage and frenzy will pull down more in half an hour than prudence, deliberation, and foresight can build up in a hundred years.” - Edmund Burke,
“The first and simplest emotion which we discover in the human mind is curiosity.” - Edmund Burke,
“Example is the school of mankind.” - Edmund Burke,
“Justice is itself the great standing policy of civil society.” - Edmund Burke,
“Liberty must be limited in order to be possessed.” - Edmund Burke,
“A state without the means of some change is without the means of its conservation.” - Edmund Burke,
“The only real voyage of discovery consists not in seeking new landscapes but in having new eyes.” - Marcel Proust,
“We are healed of a suffering only by experiencing it to the full.” - Marcel Proust,
“Happiness is beneficial for the body, but it is grief that develops the powers of the mind.” - Marcel Proust,
“The remembrance of things past is not necessarily the remembrance of things as they were.” - Marcel Proust,
“Time, which changes people, does not alter the image we have retained of them.” - Marcel Proust,
“The real voyage of discovery is not in seeking new landscapes.” - Marcel Proust,
“Desire makes everything blossom.” - Marcel Proust,
];